cust_defconfig: Disable IPC_LOGGING
Fixing undefined references
undefined reference to `ipc_log_string'

Change-Id: Ib4d96cb5195c2ae3d221b0feee60eede6f7775c6
Signed-off-by: Panchajanya1999 <panchajanya@azure-dev.live>
(cherry picked from commit 547618a74e70362348efacfd1406ca8187e25087)